// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveTrainCommand.h"
#include "Commands/FeederIdle.h"
#include "Commands/FeederPull.h"
#include "Commands/FeederPush.h"
#include "Commands/LauncherDown.h"
#include "Commands/LauncherIdle.h"
#include "Commands/LauncherTrigger.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	joystickMain = new Joystick(1);
	
	feederReverse = new JoystickButton(joystickMain, 8);
	feederReverse->WhileHeld(new FeederPush());
	launcherReset = new JoystickButton(joystickMain, 7);
	launcherReset->WhileHeld(new LauncherDown());
	launch = new JoystickButton(joystickMain, 5);
	launch->WhenPressed(new LauncherTrigger());
	feed = new JoystickButton(joystickMain, 6);
	feed->WhileHeld(new FeederPull());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("AutonomousCommand", new AutonomousCommand());
	SmartDashboard::PutData("DriveTrainCommand", new DriveTrainCommand());
	SmartDashboard::PutData("FeederPull", new FeederPull());
	SmartDashboard::PutData("FeederIdle", new FeederIdle());
	SmartDashboard::PutData("LauncherIdle", new LauncherIdle());
	SmartDashboard::PutData("LauncherTrigger", new LauncherTrigger());
	SmartDashboard::PutData("LauncherDown", new LauncherDown());
	SmartDashboard::PutData("FeederPush", new FeederPush());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getjoystickMain() {
	return joystickMain;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
