// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveForwardCommand.h"
#include "Commands/DriveTrainCommand.h"
#include "Commands/FeederIdleCommand.h"
#include "Commands/FeederPassingCommand.h"
#include "Commands/FeederPullCommand.h"
#include "Commands/FeederPushCommand.h"
#include "Commands/FeederSolenoidDownCommand.h"
#include "Commands/FeederSolenoidIdleCommand.h"
#include "Commands/LauncherIdleCommand.h"
#include "Commands/RegulateCompressorCommand.h"
#include "Commands/ResetLauncherCommand.h"
#include "Commands/TriggerLauncherCommand.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	joystickAlt = new Joystick(2);
	
	joyTriggerLauncher = new JoystickButton(joystickAlt, 5);
	joyTriggerLauncher->WhenPressed(new TriggerLauncherCommand());
	joyResetLauncher = new JoystickButton(joystickAlt, 7);
	joyResetLauncher->WhenPressed(new ResetLauncherCommand());
	joyFeederPush = new JoystickButton(joystickAlt, 8);
	joyFeederPush->WhileHeld(new FeederPushCommand());
	joyFeederPull = new JoystickButton(joystickAlt, 6);
	joyFeederPull->WhileHeld(new FeederPullCommand());
	joyFeederDown = new JoystickButton(joystickAlt, 1);
	joyFeederDown->WhenPressed(new FeederSolenoidDownCommand());
	joyFeederPassing = new JoystickButton(joystickAlt, 4);
	joyFeederPassing->WhenPressed(new FeederPassingCommand());
	joystickMain = new Joystick(1);
	
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("AutonomousCommand", new AutonomousCommand());
	SmartDashboard::PutData("DriveTrainCommand", new DriveTrainCommand());
	SmartDashboard::PutData("FeederPullCommand", new FeederPullCommand());
	SmartDashboard::PutData("FeederIdleCommand", new FeederIdleCommand());
	SmartDashboard::PutData("LauncherIdleCommand", new LauncherIdleCommand());
	SmartDashboard::PutData("TriggerLauncherCommand", new TriggerLauncherCommand());
	SmartDashboard::PutData("ResetLauncherCommand", new ResetLauncherCommand());
	SmartDashboard::PutData("FeederPushCommand", new FeederPushCommand());
	SmartDashboard::PutData("RegulateCompressorCommand", new RegulateCompressorCommand());
	SmartDashboard::PutData("FeederSolenoidIdleCommand", new FeederSolenoidIdleCommand());
	SmartDashboard::PutData("FeederSolenoidDownCommand", new FeederSolenoidDownCommand());
	SmartDashboard::PutData("FeederPassingCommand", new FeederPassingCommand());
	SmartDashboard::PutData("DriveForwardCommand", new DriveForwardCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getjoystickAlt() {
	return joystickAlt;
}
Joystick* OI::getjoystickMain() {
	return joystickMain;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
