// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.



#ifndef AUTOLAUNCHCOMMAND_H
#define AUTOLAUNCHCOMMAND_H

#include "Commands/CommandGroup.h"
#include "../Robot.h"
#include "Commands/Subsystem.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutoLaunchCommand: public CommandGroup {
public:	
	AutoLaunchCommand();
};

#endif
