// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveTrain.h"
#include "../Robotmap.h"
#include "../Commands/DriveTrainCommand.h"
#include "math.h"
#include "SmartDashboard/SmartDashboard.h"
DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
	//Declarations of speed controllers and the drive controller.
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	speedControllerRR = RobotMap::driveTrainSpeedControllerRR;
	speedControllerRL = RobotMap::driveTrainSpeedControllerRL;
	speedControllerFR = RobotMap::driveTrainSpeedControllerFR;
	speedControllerFL = RobotMap::driveTrainSpeedControllerFL;
	omniDrive = RobotMap::driveTrainOmniDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void DriveTrain::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new DriveTrainCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
//drive, the only non-init method in the class, takes telop joystick input and maps it to the mecanum drive.
void DriveTrain::drive (Joystick *joystick){
	float calcX, calcY, calcZ;
	
	//Calculates curves for the x and y inputs. Halves the z input. This is to ease power on the drivetrain,
	//preventing damage to it.
	calcX = pow(joystick->GetX(),3);
	calcY = pow(joystick->GetY(),3);
	calcZ = (joystick->GetZ()/2);
	
	//Adds calculated joy inputs to SmartDashboard.
	SmartDashboard::PutNumber("Calculated X", (double)(calcX));
	SmartDashboard::PutNumber("Calculated Y", (double)(calcY));
	SmartDashboard::PutNumber("Calculated Z", (double)(calcZ));
	
	omniDrive->MecanumDrive_Cartesian(calcX, calcY, calcZ);
	Wait(0.005);
}
void DriveTrain::driveforward(bool ison) {
	if (ison){
		omniDrive->MecanumDrive_Cartesian(0,1,0);
	}
	else {
		omniDrive->MecanumDrive_Cartesian(0,0,0);
	}
}
