// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Launcher.h"
#include "../Robotmap.h"
#include "../Commands/LauncherIdle.h"
Launcher::Launcher() : Subsystem("Launcher") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	speedControllerLauncher = RobotMap::launcherSpeedControllerLauncher;
	launcherDown = RobotMap::launcherLauncherDown;
	launcherUp = RobotMap::launcherLauncherUp;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Launcher::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new LauncherIdle());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void Launcher::reset() {
	while (launcherDown->Get() == false) {
		speedControllerLauncher->Set(-1,0);
		Wait(0.005);
	}
	speedControllerLauncher->Set(0,0);
	Wait(0.005);
}
void Launcher::launch() {
	while (launcherUp->Get() == false) {
		speedControllerLauncher->Set(1,0);
		Wait(0.005);
	}
	speedControllerLauncher->Set(0,0);
	Wait(0.005);
}
void Launcher::stop() {
	speedControllerLauncher->Set(0,0);
}
