// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Launcher.h"
#include "../Robotmap.h"
#include "../Commands/LauncherIdleCommand.h"
Launcher::Launcher() : Subsystem("Launcher") {
	//Declarations for the speed controller and limit switches for the launcher.
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	limitLauncherUp = RobotMap::launcherLimitLauncherUp;
	speedController = RobotMap::launcherSpeedController;
	limitLauncherDown = RobotMap::launcherLimitLauncherDown;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Launcher::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new LauncherIdleCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Launcher::Reset() {
	while (limitLauncherDown->Get()) {
		speedController->Set(-1,0);
	}
	speedController->Set(0,0);
}
void Launcher::Stop() {
	speedController->Set(0,0);
}
void Launcher::Launch() {
	/*SmartDashboard::PutBoolean("FeederSwitch", Robot::feeder->limitSwitch->Get());
	SmartDashboard::PutBoolean("LauncherUp", limitLauncherUp->Get());
	SmartDashboard::PutBoolean("LauncherDown", limitLauncherDown->Get());*/
	while (limitLauncherUp->Get()) {
		speedController->Set(1,0);
	}
	speedController->Set(0,0);
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
