// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Launcher.h"
#include "../Robotmap.h"
#include "../Commands/LauncherIdleCommand.h"
Launcher::Launcher() : Subsystem("Launcher") {
	//Declarations for the speed controller and limit switches for the launcher.
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	speedController = RobotMap::launcherSpeedController;
	limitLauncherDown = RobotMap::launcherlimitLauncherDown;
	limitLauncherUp = RobotMap::launcherlimitLauncherUp;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Launcher::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new LauncherIdleCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void Launcher::Reset() {
	//Sets the launcher's motor to full reverse until the limit switch on the bottom of the launcher is triggered.
	//This allows the launcher to be loaded.
	while (limitLauncherDown->Get() == false) {
		speedController->Set(-1,0);
		Wait(0.005);
	}
	speedController->Set(0,0);
	Wait(0.005);
}
void Launcher::Launch() {
	//Sets the motor to full forward until the limit switch on the top of the launcher is triggered.
	//This is actually what launches the loaded ball.
	while (limitLauncherUp->Get() == false) {
		speedController->Set(1,0);
		Wait(0.005);
	}
	speedController->Set(0,0);
	Wait(0.005);
}
void Launcher::Stop() {
	speedController->Set(0,0);
}
